'use client';

import React, { useState } from 'react';
import { 
  FileText, Search, Zap, Layout, Target, Sparkles, AlertCircle, 
  CheckCircle2, ArrowRight, ChevronDown, ChevronRight, BarChart, 
  ShieldCheck, Award, Users, Globe, BookOpen, 
  Clock, Server, Terminal, Filter, GraduationCap
} from 'lucide-react';
import Link from 'next/link';
import { CAREER_TIPS_DB } from '@/lib/career-tips-db';

const FAQS = [
  {
    q: "What is an ATS score and how is it calculated?",
    a: "An ATS score is a numerical value (often out of 100) that indicates how well your resume matches a specific job description. The software looks for keywords, job titles, years of experience, and specific skills. Higher alignment results in a higher score, which usually pushes your profile to the top of the recruiter's list."
  },
  {
    q: "Can Applicant Tracking Systems really read PDF files?",
    a: "Yes, modern ATS systems can read PDF files perfectly fine, provided the PDF is text-based and not a scanned image. A 'text-based' PDF allows you to highlight and copy the text. All resumes generated by FreeResume.dev are high-quality, text-based PDFs that are 100% ATS-compatible."
  },
  {
    q: "What is the best resume format for ATS in 2026?",
    a: "The reverse-chronological, single-column format remains the gold standard for ATS compatibility. It lists your work history starting with your current or most recent job, which is exactly how recruiters and software expect to find information."
  },
  {
    q: "How many keywords should I include in my resume?",
    a: "Quality is better than quantity. You should naturally weave in 10-15 key skills and terms throughout your resume. Avoid 'keyword stuffing' (listing skills in a giant block at the bottom), as modern ATS systems and human recruiters can detect this and may penalize your application."
  },
  {
    q: "Do resume templates affect ATS ranking?",
    a: "Absolutely. Complex templates with overlapping elements, infographics, icons for contact info, or multi-column grids can confuse the 'parser'—the part of the software that reads the text. Stick to proven, professionally designed templates like our 'Classic Professional' to stay safe."
  },
  {
    q: "Is a 2-page resume okay for an ATS?",
    a: "Yes, an ATS doesn't care about page count as much as a human does. However, for freshers and those with under 10 years of experience, a 1-page resume is still highly recommended to ensure human recruiters don't lose interest."
  }
];

export default function TipsPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeCategory, setActiveCategory] = useState<string>('All');

  const tipsList = Object.values(CAREER_TIPS_DB);
  const categories = ['All', 'ATS Optimization', 'Formatting & Layout', 'Career Guidance', 'Indian MNC Preparation'];

  const filteredTips = activeCategory === 'All' 
    ? tipsList 
    : tipsList.filter(tip => tip.category === activeCategory);

  return (
    <div className="min-h-screen bg-[#fafafa] text-gray-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-24 space-y-24">
        
        {/* --- HERO SECTION --- */}
        <div className="relative text-center space-y-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-50 text-indigo-700 rounded-full text-xs font-bold tracking-wide uppercase">
            <BookOpen size={14} /> Career Resources & ATS Learning Hub
          </div>
          <h1 className="text-5xl md:text-7xl font-black text-gray-900 tracking-tight leading-[1.1] max-w-4xl mx-auto">
            Crack the <span className="text-indigo-600">MNC Filters</span> <br/> & Secure High Packages
          </h1>
          <p className="text-xl md:text-2xl text-gray-400 max-w-3xl mx-auto font-medium leading-relaxed">
            Stop getting weeded out by automated software. Browse through our 30+ expert-written guidelines to optimize your CV and clear off-campus screening rounds.
          </p>

          <div className="flex flex-wrap justify-center gap-6 pt-4 text-xs font-bold text-gray-400 uppercase tracking-widest">
            <div className="flex items-center gap-1.5">
              <CheckCircle2 size={16} className="text-indigo-500" /> Free Resources
            </div>
            <div className="flex items-center gap-1.5">
              <CheckCircle2 size={16} className="text-indigo-500" /> India Placement Ready
            </div>
            <div className="flex items-center gap-1.5">
              <CheckCircle2 size={16} className="text-indigo-500" /> ATS Scoring Pro
            </div>
          </div>
        </div>

        {/* --- HOW RECRUITMENT SOFTWARE WORKS --- */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center bg-white border border-slate-100 rounded-[3rem] p-8 md:p-16 shadow-sm">
          <div className="space-y-6">
            <h2 className="text-3xl md:text-4xl font-black text-gray-900 tracking-tight">Understanding Applicant Tracking Systems (ATS)</h2>
            <div className="prose prose-slate max-w-none text-slate-500 space-y-4 text-sm md:text-base leading-relaxed">
              <p>
                An <strong>Applicant Tracking System (ATS)</strong> is a database software utilized by high-volume employers like TCS, Cognizant, Wipro, and global brands to capture, filter, and score candidate resumes automatically.
              </p>
              <p>
                When you submit your application, older or less sophisticated parsers convert your PDF into standard text blocks. If you use floating elements, rating bars, or tables, the text splits incorrectly, leading to a zero-match score.
              </p>
              <p>
                Our system guarantees your resume is constructed with clean text streams and responsive padding parameters, assuring complete readability metrics on 100% of industry-standard tracking portals.
              </p>
            </div>
            
            <div className="p-6 bg-indigo-50 rounded-2xl border border-indigo-100 italic text-sm font-semibold text-indigo-900">
              "Over 75% of fresher applications are filtered out algorithmically before ever being reviewed by a human recruiter in India."
            </div>
          </div>

          <div className="bg-slate-50 p-8 rounded-3xl border space-y-6 relative overflow-hidden">
            <h3 className="text-xl font-bold text-gray-900 flex items-center gap-2">
              <BarChart className="text-indigo-600" size={20} /> Optimization Scoring Metrics
            </h3>
            <div className="space-y-4">
              {[
                { label: 'Primary Sourcing Matching', val: '95% Match Ratio', desc: 'Keyword alignments matching standard job roles.' },
                { label: 'Formatting Integrity checks', val: 'Pass Guarantee', desc: 'Eliminates tables, headers, and footer distortions.' },
                { label: 'Academic cutoff standards', val: '60% / 6.0 CGPA', desc: 'Ensures board percentages are accurately indexed.' }
              ].map((item, idx) => (
                <div key={idx} className="bg-white p-4 rounded-xl border border-slate-200/60 shadow-xs">
                  <div className="flex justify-between items-center mb-1">
                    <span className="font-bold text-slate-800 text-sm">{item.label}</span>
                    <span className="text-[10px] font-bold uppercase text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-md">{item.val}</span>
                  </div>
                  <p className="text-xs text-slate-400 font-medium">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* --- LEARNING CENTER CATEGORIES FILTER --- */}
        <section className="space-y-8">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-6 border-b border-gray-200">
            <div className="space-y-2">
              <h2 className="text-3xl font-black text-gray-900 tracking-tight">Our Career Resources</h2>
              <p className="text-slate-400 text-sm font-medium">Explore 30+ highly-detailed preparation resources to land corporate jobs.</p>
            </div>

            {/* Filter buttons */}
            <div className="flex flex-wrap gap-2">
              {categories.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveCategory(cat)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                    activeCategory === cat 
                      ? 'bg-indigo-600 text-white shadow-md shadow-indigo-100' 
                      : 'bg-white border border-gray-200 text-slate-600 hover:bg-slate-50'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Dynamic filtered list */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {filteredTips.map((tip) => (
              <div 
                key={tip.slug} 
                className="bg-white border border-gray-200/80 rounded-[2.5rem] p-8 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center gap-3 mb-6">
                    <span className="px-2.5 py-1 bg-indigo-50 text-indigo-700 rounded-lg text-[10px] font-bold uppercase">
                      {tip.category}
                    </span>
                    <span className="text-slate-300">|</span>
                    <span className="text-xs font-bold text-slate-400 flex items-center gap-1">
                      <Clock size={12} /> {tip.readTime}
                    </span>
                  </div>

                  <h3 className="text-xl font-bold text-slate-900 mb-3 tracking-tight leading-snug">
                    {tip.title}
                  </h3>
                  <p className="text-slate-500 text-sm mb-6 leading-relaxed">
                    {tip.description}
                  </p>
                </div>

                <div className="pt-6 border-t border-slate-100 flex items-center justify-between">
                  <span className="text-xs font-semibold text-slate-400">{tip.date}</span>
                  <Link 
                    href={`/tips/${tip.slug}`}
                    className="text-indigo-600 font-bold text-sm inline-flex items-center gap-1.5 hover:gap-2.5 transition-all"
                  >
                    Read Resource <ChevronRight size={16} />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* --- FREQUENTLY REJECTED SHIELD STATEMENTS --- */}
        <section className="bg-slate-900 rounded-[4rem] p-12 md:p-20 text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/15 rounded-full -mr-48 -mt-48 blur-[100px]"></div>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 items-center relative z-10">
            <div className="lg:col-span-5 space-y-6">
              <h2 className="text-4xl md:text-5xl font-black tracking-tight leading-tight">Common Layout Killers To Avoid</h2>
              <p className="text-indigo-100/70 text-base leading-relaxed">
                Indian graduates frequently commit these critical formatting mistakes, leading to immediate algorithmic rejections by MNC scanners:
              </p>
              <div className="flex gap-4 pt-2">
                <div className="bg-white/5 p-4 rounded-2xl border border-white/10 text-center flex-1">
                  <span className="block text-2xl font-extrabold text-indigo-400">92%</span>
                  <p className="text-[10px] text-indigo-100/60 font-semibold tracking-wider">Formatting Rejections</p>
                </div>
                <div className="bg-white/5 p-4 rounded-2xl border border-white/10 text-center flex-1">
                  <span className="block text-2xl font-extrabold text-indigo-400">100%</span>
                  <p className="text-[10px] text-indigo-100/60 font-semibold tracking-wider">ATS safe with our builder</p>
                </div>
              </div>
            </div>

            <div className="lg:col-span-7 grid grid-cols-1 md:grid-cols-2 gap-6 text-sm">
              <div className="p-6 bg-white/5 rounded-3xl border border-white/10">
                <h4 className="font-bold text-lg mb-2">Unparseable Fonts</h4>
                <p className="opacity-70 leading-relaxed text-xs">Avoid using complex Google display families. Safe options include Inter, Roboto, Calibri, and standard system helveticas.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-3xl border border-white/10">
                <h4 className="font-bold text-lg mb-2">Non-Text PDF formats</h4>
                <p className="opacity-70 leading-relaxed text-xs">Never host scanned images of your resume. Modern tools scan digital vectors. Check if your text is copy-pasteable before submitting.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-3xl border border-white/10">
                <h4 className="font-bold text-lg mb-2">Multi-Column Overlaps</h4>
                <p className="opacity-70 leading-relaxed text-xs">Dual-column layouts are extremely difficult for older parsers to scan correctly. Stick to clean, top-to-bottom single-column structures.</p>
              </div>
              <div className="p-6 bg-white/5 rounded-3xl border border-white/10">
                <h4 className="font-bold text-lg mb-2">Skills Rating Bars</h4>
                <p className="opacity-70 leading-relaxed text-xs">Do not rate your skills with stars (e.g., Python 4/5). Computeras cannot read graphical parameters and will rate your skill competency as zero.</p>
              </div>
            </div>
          </div>
        </section>

        {/* --- FAQ COLLAPSIBLES ACCORDION --- */}
        <section className="bg-white border border-slate-100 rounded-[3rem] p-8 md:p-16 shadow-sm max-w-4xl mx-auto space-y-12">
          <div className="text-center space-y-3">
            <h2 className="text-3xl font-black text-slate-900 tracking-tight">Frequently Asked Questions</h2>
            <p className="text-slate-400 text-sm font-medium">Quick answers to the most common questions about ATS optimization.</p>
          </div>
          
          <div className="space-y-4">
            {FAQS.map((faq, idx) => (
              <div key={idx} className="bg-slate-50 rounded-2xl border overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full text-left p-6 flex justify-between items-center hover:bg-slate-100/50 transition-colors focus:outline-none"
                >
                  <span className="font-bold text-slate-800 text-base md:text-lg pr-4">{faq.q}</span>
                  <div className={`p-2 rounded-xl transition-all ${openFaq === idx ? 'bg-indigo-600 text-white' : 'bg-white border text-indigo-600'}`}>
                    <ChevronDown size={18} className={`transition-transform duration-200 ${openFaq === idx ? 'rotate-180' : ''}`} />
                  </div>
                </button>
                {openFaq === idx && (
                  <div className="p-6 pt-0 text-slate-500 leading-relaxed text-sm md:text-base">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* --- CLOSING CALL TO ACTION --- */}
        <div className="bg-indigo-600 rounded-[3.5rem] p-12 md:p-20 text-white text-center shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full -mr-48 -mt-48 blur-3xl"></div>
          <h2 className="text-4xl md:text-6xl font-black mb-8 leading-tight tracking-tight relative z-10">Start Your Professional <br/> Journey Successfully</h2>
          <p className="text-indigo-100 text-xl md:text-2xl mb-12 max-w-3xl mx-auto font-medium relative z-10">
            Utilize our free recruiter-verified tools and templates to construct an ATS-compliant resume and clear screening rounds instantly.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-6 relative z-10">
            <Link href="/" className="bg-white text-indigo-600 hover:bg-indigo-50 px-12 py-5 rounded-2xl font-bold text-xl transition-all shadow-xl">
              Create My Resume Now
            </Link>
            <Link href="/resume-examples" className="bg-indigo-500/30 border-2 border-indigo-400 text-white hover:bg-indigo-500/50 px-12 py-5 rounded-2xl font-bold text-xl transition-all">
              Browse Role Samples
            </Link>
          </div>
        </div>
      </main>

      <footer className="bg-white border-t border-slate-200 py-12 mt-20">
        <div className="max-w-7xl mx-auto px-4 text-center space-y-4">
          <p className="text-slate-400 text-sm font-medium">
            &copy; {new Date().getFullYear()} FreeResume.dev - Empowering Indian Graduates to Land Their First Job.
          </p>
          <div className="flex justify-center gap-8 text-xs font-bold text-slate-400 uppercase tracking-widest">
            <Link href="/privacy" className="hover:text-indigo-600">Privacy Policy</Link>
            <Link href="/terms" className="hover:text-indigo-600">Terms of Use</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
